from dataclasses import dataclass


@dataclass
class ServerListItem:
    virtualserver_autostart: int
    virtualserver_clientsonline: int
    virtualserver_id: int
    virtualserver_machine_id: str
    virtualserver_maxclients: int
    virtualserver_name: str
    virtualserver_port: int
    virtualserver_queryclientsonline: int
    virtualserver_status: str
    virtualserver_uptime: int

    @staticmethod
    def from_dict(data: dict) -> 'ServerListItem':
        return ServerListItem(
            virtualserver_autostart=int(data.get('virtualserver_autostart', 0)),
            virtualserver_clientsonline=int(data.get('virtualserver_clientsonline', 0)),
            virtualserver_id=int(data.get('virtualserver_id', 0)),
            virtualserver_machine_id=data.get('virtualserver_machine_id', ''),
            virtualserver_maxclients=int(data.get('virtualserver_maxclients', 0)),
            virtualserver_name=data.get('virtualserver_name', ''),
            virtualserver_port=int(data.get('virtualserver_port', 0)),
            virtualserver_queryclientsonline=int(data.get('virtualserver_queryclientsonline', 0)),
            virtualserver_status=data.get('virtualserver_status', ''),
            virtualserver_uptime=int(data.get('virtualserver_uptime', 0)),
        )


@dataclass
class ServerInfo:
    connection_bandwidth_received_last_minute_total: int
    connection_bandwidth_received_last_second_total: int
    connection_bandwidth_sent_last_minute_total: int
    connection_bandwidth_sent_last_second_total: int
    connection_bytes_received_control: int
    connection_bytes_received_keepalive: int
    connection_bytes_received_speech: int
    connection_bytes_received_total: int
    connection_bytes_sent_control: int
    connection_bytes_sent_keepalive: int
    connection_bytes_sent_speech: int
    connection_bytes_sent_total: int
    connection_filetransfer_bandwidth_received: int
    connection_filetransfer_bandwidth_sent: int
    connection_filetransfer_bytes_received_total: int
    connection_filetransfer_bytes_sent_total: int
    connection_packets_received_control: int
    connection_packets_received_keepalive: int
    connection_packets_received_speech: int
    connection_packets_received_total: int
    connection_packets_sent_control: int
    connection_packets_sent_keepalive: int
    connection_packets_sent_speech: int
    connection_packets_sent_total: int
    virtualserver_antiflood_points_needed_command_block: int
    virtualserver_antiflood_points_needed_ip_block: int
    virtualserver_antiflood_points_needed_plugin_block: int
    virtualserver_antiflood_points_tick_reduce: int
    virtualserver_ask_for_privilegekey: int
    virtualserver_autostart: int
    virtualserver_capability_extensions: str
    virtualserver_channel_temp_delete_delay_default: int
    virtualserver_channelsonline: int
    virtualserver_client_connections: int
    virtualserver_clientsonline: int
    virtualserver_codec_encryption_mode: int
    virtualserver_complain_autoban_count: int
    virtualserver_complain_autoban_time: int
    virtualserver_complain_remove_time: int
    virtualserver_created: int
    virtualserver_default_channel_admin_group: int
    virtualserver_default_channel_group: int
    virtualserver_default_server_group: int
    virtualserver_download_quota: int
    virtualserver_file_storage_class: str
    virtualserver_filebase: str
    virtualserver_flag_password: int
    virtualserver_hostbanner_gfx_interval: int
    virtualserver_hostbanner_gfx_url: str
    virtualserver_hostbanner_mode: int
    virtualserver_hostbanner_url: str
    virtualserver_hostbutton_gfx_url: str
    virtualserver_hostbutton_tooltip: str
    virtualserver_hostbutton_url: str
    virtualserver_hostmessage: str
    virtualserver_hostmessage_mode: int
    virtualserver_icon_id: int
    virtualserver_id: int
    virtualserver_ip: str
    virtualserver_log_channel: int
    virtualserver_log_client: int
    virtualserver_log_filetransfer: int
    virtualserver_log_permissions: int
    virtualserver_log_query: int
    virtualserver_log_server: int
    virtualserver_machine_id: str
    virtualserver_max_download_total_bandwidth: int
    virtualserver_max_upload_total_bandwidth: int
    virtualserver_maxclients: int
    virtualserver_min_android_version: int
    virtualserver_min_client_version: int
    virtualserver_min_clients_in_channel_before_forced_silence: int
    virtualserver_min_ios_version: int
    virtualserver_month_bytes_downloaded: int
    virtualserver_month_bytes_uploaded: int
    virtualserver_name: str
    virtualserver_name_phonetic: str
    virtualserver_needed_identity_security_level: int
    virtualserver_nickname: str
    virtualserver_password: str
    virtualserver_platform: str
    virtualserver_port: int
    virtualserver_priority_speaker_dimm_modificator: float
    virtualserver_query_client_connections: int
    virtualserver_queryclientsonline: int
    virtualserver_reserved_slots: int
    virtualserver_status: str
    virtualserver_total_bytes_downloaded: int
    virtualserver_total_bytes_uploaded: int
    virtualserver_total_packetloss_control: float
    virtualserver_total_packetloss_keepalive: float
    virtualserver_total_packetloss_speech: float
    virtualserver_total_packetloss_total: float
    virtualserver_total_ping: float
    virtualserver_unique_identifier: str
    virtualserver_upload_quota: int
    virtualserver_uptime: int
    virtualserver_version: str
    virtualserver_weblist_enabled: int
    virtualserver_welcomemessage: str

    @staticmethod
    def from_dict(data: dict) -> 'ServerInfo':
        return ServerInfo(
            connection_bandwidth_received_last_minute_total=int(data.get('connection_bandwidth_received_last_minute_total', 0)),
            connection_bandwidth_received_last_second_total=int(data.get('connection_bandwidth_received_last_second_total', 0)),
            connection_bandwidth_sent_last_minute_total=int(data.get('connection_bandwidth_sent_last_minute_total', 0)),
            connection_bandwidth_sent_last_second_total=int(data.get('connection_bandwidth_sent_last_second_total', 0)),
            connection_bytes_received_control=int(data.get('connection_bytes_received_control', 0)),
            connection_bytes_received_keepalive=int(data.get('connection_bytes_received_keepalive', 0)),
            connection_bytes_received_speech=int(data.get('connection_bytes_received_speech', 0)),
            connection_bytes_received_total=int(data.get('connection_bytes_received_total', 0)),
            connection_bytes_sent_control=int(data.get('connection_bytes_sent_control', 0)),
            connection_bytes_sent_keepalive=int(data.get('connection_bytes_sent_keepalive', 0)),
            connection_bytes_sent_speech=int(data.get('connection_bytes_sent_speech', 0)),
            connection_bytes_sent_total=int(data.get('connection_bytes_sent_total', 0)),
            connection_filetransfer_bandwidth_received=int(data.get('connection_filetransfer_bandwidth_received', 0)),
            connection_filetransfer_bandwidth_sent=int(data.get('connection_filetransfer_bandwidth_sent', 0)),
            connection_filetransfer_bytes_received_total=int(data.get('connection_filetransfer_bytes_received_total', 0)),
            connection_filetransfer_bytes_sent_total=int(data.get('connection_filetransfer_bytes_sent_total', 0)),
            connection_packets_received_control=int(data.get('connection_packets_received_control', 0)),
            connection_packets_received_keepalive=int(data.get('connection_packets_received_keepalive', 0)),
            connection_packets_received_speech=int(data.get('connection_packets_received_speech', 0)),
            connection_packets_received_total=int(data.get('connection_packets_received_total', 0)),
            connection_packets_sent_control=int(data.get('connection_packets_sent_control', 0)),
            connection_packets_sent_keepalive=int(data.get('connection_packets_sent_keepalive', 0)),
            connection_packets_sent_speech=int(data.get('connection_packets_sent_speech', 0)),
            connection_packets_sent_total=int(data.get('connection_packets_sent_total', 0)),
            virtualserver_antiflood_points_needed_command_block=int(data.get('virtualserver_antiflood_points_needed_command_block', 0)),
            virtualserver_antiflood_points_needed_ip_block=int(data.get('virtualserver_antiflood_points_needed_ip_block', 0)),
            virtualserver_antiflood_points_needed_plugin_block=int(data.get('virtualserver_antiflood_points_needed_plugin_block', 0)),
            virtualserver_antiflood_points_tick_reduce=int(data.get('virtualserver_antiflood_points_tick_reduce', 0)),
            virtualserver_ask_for_privilegekey=int(data.get('virtualserver_ask_for_privilegekey', 0)),
            virtualserver_autostart=int(data.get('virtualserver_autostart', 0)),
            virtualserver_capability_extensions=str(data.get('virtualserver_capability_extensions', '')),
            virtualserver_channel_temp_delete_delay_default=int(data.get('virtualserver_channel_temp_delete_delay_default', 0)),
            virtualserver_channelsonline=int(data.get('virtualserver_channelsonline', 0)),
            virtualserver_client_connections=int(data.get('virtualserver_client_connections', 0)),
            virtualserver_clientsonline=int(data.get('virtualserver_clientsonline', 0)),
            virtualserver_codec_encryption_mode=int(data.get('virtualserver_codec_encryption_mode', 0)),
            virtualserver_complain_autoban_count=int(data.get('virtualserver_complain_autoban_count', 0)),
            virtualserver_complain_autoban_time=int(data.get('virtualserver_complain_autoban_time', 0)),
            virtualserver_complain_remove_time=int(data.get('virtualserver_complain_remove_time', 0)),
            virtualserver_created=int(data.get('virtualserver_created', 0)),
            virtualserver_default_channel_admin_group=int(data.get('virtualserver_default_channel_admin_group', 0)),
            virtualserver_default_channel_group=int(data.get('virtualserver_default_channel_group', 0)),
            virtualserver_default_server_group=int(data.get('virtualserver_default_server_group', 0)),
            virtualserver_download_quota=int(data.get('virtualserver_download_quota', 0)),
            virtualserver_file_storage_class=str(data.get('virtualserver_file_storage_class', '')),
            virtualserver_filebase=str(data.get('virtualserver_filebase', '')),
            virtualserver_flag_password=int(data.get('virtualserver_flag_password', 0)),
            virtualserver_hostbanner_gfx_interval=int(data.get('virtualserver_hostbanner_gfx_interval', 0)),
            virtualserver_hostbanner_gfx_url=str(data.get('virtualserver_hostbanner_gfx_url', '')),
            virtualserver_hostbanner_mode=int(data.get('virtualserver_hostbanner_mode', 0)),
            virtualserver_hostbanner_url=str(data.get('virtualserver_hostbanner_url', '')),
            virtualserver_hostbutton_gfx_url=str(data.get('virtualserver_hostbutton_gfx_url', '')),
            virtualserver_hostbutton_tooltip=str(data.get('virtualserver_hostbutton_tooltip', '')),
            virtualserver_hostbutton_url=str(data.get('virtualserver_hostbutton_url', '')),
            virtualserver_hostmessage=str(data.get('virtualserver_hostmessage', '')),
            virtualserver_hostmessage_mode=int(data.get('virtualserver_hostmessage_mode', 0)),
            virtualserver_icon_id=int(data.get('virtualserver_icon_id', 0)),
            virtualserver_id=int(data.get('virtualserver_id', 0)),
            virtualserver_ip=str(data.get('virtualserver_ip', '')),
            virtualserver_log_channel=int(data.get('virtualserver_log_channel', 0)),
            virtualserver_log_client=int(data.get('virtualserver_log_client', 0)),
            virtualserver_log_filetransfer=int(data.get('virtualserver_log_filetransfer', 0)),
            virtualserver_log_permissions=int(data.get('virtualserver_log_permissions', 0)),
            virtualserver_log_query=int(data.get('virtualserver_log_query', 0)),
            virtualserver_log_server=int(data.get('virtualserver_log_server', 0)),
            virtualserver_machine_id=str(data.get('virtualserver_machine_id', '')),
            virtualserver_max_download_total_bandwidth=int(data.get('virtualserver_max_download_total_bandwidth', 0)),
            virtualserver_max_upload_total_bandwidth=int(data.get('virtualserver_max_upload_total_bandwidth', 0)),
            virtualserver_maxclients=int(data.get('virtualserver_maxclients', 0)),
            virtualserver_min_android_version=int(data.get('virtualserver_min_android_version', 0)),
            virtualserver_min_client_version=int(data.get('virtualserver_min_client_version', 0)),
            virtualserver_min_clients_in_channel_before_forced_silence=int(data.get('virtualserver_min_clients_in_channel_before_forced_silence', 0)),
            virtualserver_min_ios_version=int(data.get('virtualserver_min_ios_version', 0)),
            virtualserver_month_bytes_downloaded=int(data.get('virtualserver_month_bytes_downloaded', 0)),
            virtualserver_month_bytes_uploaded=int(data.get('virtualserver_month_bytes_uploaded', 0)),
            virtualserver_name=str(data.get('virtualserver_name', '')),
            virtualserver_name_phonetic=str(data.get('virtualserver_name_phonetic', '')),
            virtualserver_needed_identity_security_level=int(data.get('virtualserver_needed_identity_security_level', 0)),
            virtualserver_nickname=str(data.get('virtualserver_nickname', '')),
            virtualserver_password=str(data.get('virtualserver_password', '')),
            virtualserver_platform=str(data.get('virtualserver_platform', '')),
            virtualserver_port=int(data.get('virtualserver_port', 0)),
            virtualserver_priority_speaker_dimm_modificator=float(data.get('virtualserver_priority_speaker_dimm_modificator', 0.0)),
            virtualserver_query_client_connections=int(data.get('virtualserver_query_client_connections', 0)),
            virtualserver_queryclientsonline=int(data.get('virtualserver_queryclientsonline', 0)),
            virtualserver_reserved_slots=int(data.get('virtualserver_reserved_slots', 0)),
            virtualserver_status=str(data.get('virtualserver_status', '')),
            virtualserver_total_bytes_downloaded=int(data.get('virtualserver_total_bytes_downloaded', 0)),
            virtualserver_total_bytes_uploaded=int(data.get('virtualserver_total_bytes_uploaded', 0)),
            virtualserver_total_packetloss_control=float(data.get('virtualserver_total_packetloss_control', 0.0)),
            virtualserver_total_packetloss_keepalive=float(data.get('virtualserver_total_packetloss_keepalive', 0.0)),
            virtualserver_total_packetloss_speech=float(data.get('virtualserver_total_packetloss_speech', 0.0)),
            virtualserver_total_packetloss_total=float(data.get('virtualserver_total_packetloss_total', 0.0)),
            virtualserver_total_ping=float(data.get('virtualserver_total_ping', 0.0)),
            virtualserver_unique_identifier=str(data.get('virtualserver_unique_identifier', '')),
            virtualserver_upload_quota=int(data.get('virtualserver_upload_quota', 0)),
            virtualserver_uptime=int(data.get('virtualserver_uptime', 0)),
            virtualserver_version=str(data.get('virtualserver_version', '')),
            virtualserver_weblist_enabled=int(data.get('virtualserver_weblist_enabled', 0)),
            virtualserver_welcomemessage=str(data.get('virtualserver_welcomemessage', ''))
        )
