class ReasonId:
    """Reason for a client kick (clientkick reasonid)."""
    KICK_FROM_CHANNEL = 4
    KICK_FROM_SERVER = 5


class TargetMode:
    """Target mode for sendtextmessage."""
    CLIENT = 1
    CHANNEL = 2
    SERVER = 3


class GroupType:
    """Type of server/channel group (servergrouplist/channelgrouplist `type`)."""
    TEMPLATE = 0
    REGULAR = 1
    QUERY = 2


class LogLevel:
    """Log level for logadd."""
    ERROR = 1
    WARNING = 2
    DEBUG = 3
    INFO = 4


class ErrorCode:
    """Frequent ``TeamSpeakAPIError.code`` values, e.g. ``exc.code == ErrorCode.INSUFFICIENT_PERMISSIONS``."""
    OK = 0
    UNDEFINED = 1
    NOT_IMPLEMENTED = 2
    OUT_OF_MEMORY = 3
    PARAMETER_NOT_FOUND = 5
    CONNECTION_LOST = 6
    CANCELED = 7
    DATABASE = 4
    CLIENT_INVALID_ID = 512
    CLIENT_NICKNAME_INUSE = 513
    CLIENT_INVALID_ERROR_CODE = 514
    CLIENT_PROTOCOL_LIMIT_REACHED = 515
    CLIENT_INVALID_TYPE = 516
    CLIENT_ALREADY_SUBSCRIBED = 517
    CLIENT_NOT_LOGGED_IN = 518
    CLIENT_COULD_NOT_VALIDATE_IDENTITY = 519
    CLIENT_INVALID_PASSWORD = 520
    CLIENT_VERSION_OUTDATED = 521
    CLIENT_IS_FLOODING = 522
    CLIENT_HAS_BEEN_DELETED = 523
    CLIENT_IS_BANNED = 524
    CLIENT_NOT_FOUND_BY_NAME = 525
    CHANNEL_INVALID_ID = 768
    CHANNEL_PROTOCOL_LIMIT_REACHED = 769
    CHANNEL_ALREADY_IN = 770
    CHANNEL_NAME_INUSE = 771
    CHANNEL_NOT_EMPTY = 772
    CHANNEL_CAN_NOT_DELETE_DEFAULT = 773
    CHANNEL_DEFAULT_REQUIRE_PERMANENT = 774
    CHANNEL_INVALID_FLAGS = 775
    CHANNEL_PARENT_NOT_PERMANENT = 776
    CHANNEL_MAXCLIENTS_REACHED = 777
    CHANNEL_MAXFAMILY_REACHED = 778
    CHANNEL_INVALID_ORDER = 779
    CHANNEL_NO_FILETRANSFER_SUPPORTED = 780
    CHANNEL_INVALID_PASSWORD = 781
    SERVER_INVALID_ID = 1024
    SERVER_RUNNING = 1025
    SERVER_IS_SHUTTING_DOWN = 1026
    SERVER_MAXCLIENTS_REACHED = 1027
    SERVER_INVALID_PASSWORD = 1028
    SERVER_IS_NOT_RUNNING = 1031
    SERVER_NOT_SELECTED = 1035
    SERVER_NO_SUCH_SERVER = 1036
    PARAMETER_QUOTA = 1536
    PARAMETER_INVALID_COUNT = 1537
    PARAMETER_INVALID = 1538
    PARAMETER_INVALID_SIZE = 1540
    PARAMETER_MISSING = 1541
    PARAMETER_CONVERT = 1542
    DATABASE_EMPTY_RESULT = 1281
    DATABASE_DUPLICATE_ENTRY = 1282
    DATABASE_NO_MODIFICATIONS = 1283
    DATABASE_CONSTRAINT = 1284
    DATABASE_REINVOKE = 1285
    PERMISSION_INVALID_GROUP_ID = 2560
    PERMISSION_DUPLICATE_ENTRY = 2561
    PERMISSION_INVALID_PERM_ID = 2562
    PERMISSION_EMPTY_RESULT = 2563
    PERMISSION_DEFAULT_GROUP_FORBIDDEN = 2564
    PERMISSION_INVALID_SIZE = 2565
    PERMISSION_INVALID_VALUE = 2566
    PERMISSIONS_GROUP_NOT_EMPTY = 2567
    INSUFFICIENT_PERMISSIONS = 2568
    LICENSE_LIMIT_REACHED = 2816
    OUT_OF_SCOPE = 5120
